version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    depends_on:
      - phone-validator
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - development

  phone-validator:
    container_name: phone-validator
    build: ./phone-validator
    volumes:
      - './:/app'
    ports:
        - 8888:8888
    networks:
      - development

networks:
  development:
 
